Address issue in which escaped characters are not handled properly.
If a user were to use sendKey() or sendKeys() to send a character or string
that contained escaped characters (e.g. '\t' or '\n'), the escaped character
would result in an exception because it could not be found in the keyboard
constants.

This change attempts to address this by mapping the escaped characters to
their keyboard constant equivalents.

Note that this particular change does not include the entire set of
escape sequences recognized by Python.

Testing done:
-------------

>>> import os, sys, time
>>> import atomac
NOTE:  This import was conducted after
 a `python setup.py build` was issued at the shell
 and the import made above the atomac directory
 in the build directory

>>> a = atomac.getAppRefByLocalizedName('Terminal')
a.s>>> a.sendKeys('hello')
hello>>> hello
KeyboardInterrupt
>>> a.sendKeys('hello\nthere')
hello
there>>> hello
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'hello' is not defined
>>> there
KeyboardInterrupt
>>> a.sendKeys('hello\rthere')
hello
there>>> hello
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'hello' is not defined
>>> a.sendKeys('hello\r\nthere')
hello

there>>> hello
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'hello' is not defined
>>>
>>> there
KeyboardInterrupt
>>> a.sendKeys('hello\tthere')
hello	there>>> hello       there
KeyboardInterrupt
>>> a.sendKeys('hello\tthere')
KeyboardInterrupt
>>> a.sendKey('\n')

>>>
>>> a.sendKeys('\n\n\n\n\n')

>>>
>>>
>>>
>>>
>>>
>>> a.sendKeys('\t\t\t\t\t')
					>>>
KeyboardInterrupt